### ISSUE TITLE
Error with invalid directory 

### ISSUE THREAD

**Issue by filliptm** [SamKhoze/ComfyUI-DeepFuze#1]
Getting this error when executing both nodes 

Error occurred when executing DeepFuzeFaceSwap:

[WinError 267] The directory name is invalid

File "C:\Users\Filli\Desktop\Comfy_Version_Tests\ComfyUI_Copy\execution.py", line 151, in recursive_execute
output_data, output_ui = get_output_data(obj, input_data_all)
File "C:\Users\Filli\Desktop\Comfy_Version_Tests\ComfyUI_Copy\execution.py", line 81, in get_output_data
return_values = map_node_over_list(obj, input_data_all, obj.FUNCTION, allow_interrupt=True)
File "C:\Users\Filli\Desktop\Comfy_Version_Tests\ComfyUI_Copy\execution.py", line 74, in map_node_over_list
results.append(getattr(obj, func)(**slice_dict(input_data_all, i)))
File "C:\Users\Filli\Desktop\Comfy_Version_Tests\ComfyUI_Copy\custom_nodes\ComfyUI-DeepFuze\nodes.py", line 959, in faceswampgenerate
result = subprocess.run(command,cwd="ComfyUI/custom_nodes/ComfyUI-DeepFuze",stdout=subprocess.PIPE)
File "C:\Users\Filli\AppData\Local\Programs\Python\Python310\lib\subprocess.py", line 501, in run
with Popen(*popenargs, **kwargs) as process:
File "C:\Users\Filli\AppData\Local\Programs\Python\Python310\lib\subprocess.py", line 969, in __init__
self._execute_child(args, executable, preexec_fn, close_fds,
File "C:\Users\Filli\AppData\Local\Programs\Python\Python310\lib\subprocess.py", line 1438, in _execute_child
hp, ht, pid, tid = _winapi.CreateProcess(executable, args,

**Comment by SamKhoze** [comment]
Did you install it with the comfyui manager "Install with GIT ULR" or manually install it? 

I suggest deleting the node, and installing it from your comfyui manager through "Install with GIT ULR", The comfyui manager will create the path.

**Comment by guahunyo** [comment]
loadimagepath is ok
![image](https://github.com/SamKhoze/ComfyUI-DeepFuze/assets/18573180/48126594-6a34-4b3d-82f1-6c609158f0bc)
but 
![image](https://github.com/SamKhoze/ComfyUI-DeepFuze/assets/18573180/1f0d7b59-86b3-44a6-b98a-8fa32d4770da)

**Comment by SamKhoze** [comment]
<img width="620" alt="Screenshot 2024-06-19 at 11 47 59 AM" src="https://github.com/SamKhoze/ComfyUI-DeepFuze/assets/68170403/a4d1685b-c4fc-4190-b451-8336986aea98">
I tested your workflow it is working, perhaps you did not install your deepFuze correctly

**Comment by guahunyo** [comment]
> <img alt="Screenshot 2024-06-19 at 11 47 59 AM" width="620" src="https://private-user-images.githubusercontent.com/68170403/341177765-a4d1685b-c4fc-4190-b451-8336986aea98.png?jwt=eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJnaXRodWIuY29tIiwiYXVkIjoicmF3LmdpdGh1YnVzZXJjb250ZW50LmNvbSIsImtleSI6ImtleTUiLCJleHAiOjE3MTg4NTM3NTgsIm5iZiI6MTcxODg1MzQ1OCwicGF0aCI6Ii82ODE3MDQwMy8zNDExNzc3NjUtYTRkMTY4NWItYzRmYy00MTkwLWI0NTEtODMzNjk4NmFlYTk4LnBuZz9YLUFtei1BbGdvcml0aG09QVdTNC1ITUFDLVNIQTI1NiZYLUFtei1DcmVkZW50aWFsPUFLSUFWQ09EWUxTQTUzUFFLNFpBJTJGMjAyNDA2MjAlMkZ1cy1lYXN0LTElMkZzMyUyRmF3czRfcmVxdWVzdCZYLUFtei1EYXRlPTIwMjQwNjIwVDAzMTczOFomWC1BbXotRXhwaXJlcz0zMDAmWC1BbXotU2lnbmF0dXJlPWUyYTk3OWE5MzJhZTVmZmYwZGEzZjViNDVkYzljMzdkYmUxZGI2ZWU4ZGNjMDRlZjkzNDY2YzUzYjUxNjU1MGMmWC1BbXotU2lnbmVkSGVhZGVycz1ob3N0JmFjdG9yX2lkPTAma2V5X2lkPTAmcmVwb19pZD0wIn0.LtOAwBpInMjdhcw9tS1qOp1p9RFa08X39OX8QbS-1T4"> I tested your workflow it is working, perhaps you did not install your deepFuze correctly

Do I have to use comfyui manager to install it? I installed it using the command line git clone -v --recursive --progress git@github.com:SamKhoze/ComfyUI-DeepFuze.git

**Comment by guahunyo** [comment]
![image](https://github.com/SamKhoze/ComfyUI-DeepFuze/assets/18573180/1ca49e9d-d572-4416-a9ce-ce396d1e9ae3)

**Comment by SamKhoze** [comment]
@guahunyo Please make sure not to install this node via git clone unless you are experienced and familiar with building wheels for TTS. The recommended method is to install it via comfy manager. While installing, keep an eye on your terminal to spot any errors. For example, conflicting installations of NumPy or Python could cause issues. If you encounter an error, it is generally easy to fix. I apologize for the unfriendly installation process. Face swapping, lip syncing, and voice cloning are complex installations individually. I have attempted to minimize the difficulties as much as possible, but there is still work to be done.

**Comment by guahunyo** [comment]
> @guahunyo Please make sure not to install this node via git clone unless you are experienced and familiar with building wheels for TTS. The recommended method is to install it via comfy manager. While installing, keep an eye on your terminal to spot any errors. For example, conflicting installations of NumPy or Python could cause issues. If you encounter an error, it is generally easy to fix. I apologize for the unfriendly installation process. Face swapping, lip syncing, and voice cloning are complex installations individually. I have attempted to minimize the difficulties as much as possible, but there is still work to be done.

thank you
