### ISSUE TITLE
AttributeError: 'dict' object has no attribute 'sample_rate'

### ISSUE THREAD

**Issue by dancemanUK** [SamKhoze/ComfyUI-DeepFuze#12]
<img width="1609" alt="wechat_20240621220321" src="https://github.com/SamKhoze/ComfyUI-DeepFuze/assets/1702623/b557dd94-f2f8-4317-91d2-a51592feb635">

[rgthree] Using rgthree's optimized recursive execution.
None 24.0 video/h265-mp4
video h265-mp4
{'enhancer': 'None', 'frame_enhancer': 'None', 'face_mask_padding_left': 0, 'face_mask_padding_right': 0, 'face_mask_padding_bottom': 0, 'face_mask_padding_top': 0, 'trim_frame_start': 0, 'trim_frame_end': 0, 'device': 'cpu', 'frame_rate': 24.0, 'loop_count': 0, 'filename_prefix': 'deepfuze', 'pingpong': False, 'save_output': True, 'images': ['8', 0], 'audio': ['4', 0], 'format': 'video/h265-mp4', 'pix_fmt': 'yuv420p10le', 'crf': 22, 'save_metadata': ['save_metadata', 'BOOLEAN', {'default': True}]}
F:\ComfyUI_windows_portable_torch23cu121\ComfyUI\custom_nodes\ComfyUI-VideoHelperSuite\videohelpersuite\..\video_formats\h265-mp4.json
pix_fmt
crf
save_metadata
Output images were not of valid resolution and have had padding applied
!!! Exception during processing!!! 'dict' object has no attribute 'sample_rate'
Traceback (most recent call last):
  File "F:\ComfyUI_windows_portable_torch23cu121\ComfyUI\execution.py", line 151, in recursive_execute
    output_data, output_ui = get_output_data(obj, input_data_all)
  File "F:\ComfyUI_windows_portable_torch23cu121\ComfyUI\execution.py", line 81, in get_output_data
    return_values = map_node_over_list(obj, input_data_all, obj.FUNCTION, allow_interrupt=True)
  File "F:\ComfyUI_windows_portable_torch23cu121\ComfyUI\execution.py", line 74, in map_node_over_list
    results.append(getattr(obj, func)(**slice_dict(input_data_all, i)))
  File "F:\ComfyUI_windows_portable_torch23cu121\ComfyUI\custom_nodes\ComfyUI-DeepFuze\nodes.py", line 1333, in lipsyncgenerate
    write(audio_file,audio.sample_rate,audio.audio_data)
AttributeError: 'dict' object has no attribute 'sample_rate'

**Comment by SamKhoze** [comment]
@dancemanUK try to load audio via load audio file not load audio path and see if it works. 
![Screenshot 2024-06-21 at 8 42 12 AM](https://github.com/SamKhoze/ComfyUI-DeepFuze/assets/68170403/658113de-d264-45f3-a55a-f04e86186a60)

**Comment by leiweiqiang** [comment]
The issue is a conflict with Load Audio between AudioScheduler and _for_testing. 
My solution is to comment out line 1192 in ComfyUI/nodes.py: "nodes_audio.py". 
After restarting ComfyUI, Load Audio will appear in the AudioScheduler submenu.

<img width="579" alt="Screenshot 2024-06-21 at 10 32 50 PM" src="https://github.com/SamKhoze/ComfyUI-DeepFuze/assets/28274230/985343e5-4fe7-4bbc-8147-ece58397439b">

<img width="469" alt="Screenshot 2024-06-21 at 10 09 59 PM" src="https://github.com/SamKhoze/ComfyUI-DeepFuze/assets/28274230/bfbba68e-d32e-4016-ad21-80c3c9697482">

**Comment by Maelstrom2014** [comment]
> The issue is a conflict with Load Audio between AudioScheduler and _for_testing. My solution is to comment out line 1192 in ComfyUI/nodes.py: "nodes_audio.py". After restarting ComfyUI, Load Audio will appear in the AudioScheduler submenu.
> 
> <img alt="Screenshot 2024-06-21 at 10 32 50 PM" width="579" src="https://private-user-images.githubusercontent.com/28274230/341938063-985343e5-4fe7-4bbc-8147-ece58397439b.png?jwt=eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJnaXRodWIuY29tIiwiYXVkIjoicmF3LmdpdGh1YnVzZXJjb250ZW50LmNvbSIsImtleSI6ImtleTUiLCJleHAiOjE3MTk0MTE3MTksIm5iZiI6MTcxOTQxMTQxOSwicGF0aCI6Ii8yODI3NDIzMC8zNDE5MzgwNjMtOTg1MzQzZTUtNGZlNy00YmJjLTgxNDctZWNlNTgzOTc0MzliLnBuZz9YLUFtei1BbGdvcml0aG09QVdTNC1ITUFDLVNIQTI1NiZYLUFtei1DcmVkZW50aWFsPUFLSUFWQ09EWUxTQTUzUFFLNFpBJTJGMjAyNDA2MjYlMkZ1cy1lYXN0LTElMkZzMyUyRmF3czRfcmVxdWVzdCZYLUFtei1EYXRlPTIwMjQwNjI2VDE0MTY1OVomWC1BbXotRXhwaXJlcz0zMDAmWC1BbXotU2lnbmF0dXJlPTU5ZmY4OWI1NTMzMDQ1Y2Y1ZDg3NDhmMjQzNjJlYzcwMzVlZTZkMDYzYWI0OGNjYzFmMzEwOTJkMGQ3OGFjZmImWC1BbXotU2lnbmVkSGVhZGVycz1ob3N0JmFjdG9yX2lkPTAma2V5X2lkPTAmcmVwb19pZD0wIn0.GP6vs-PpifyClwWGLSaDcrTbuTkEe0IxWtjNi91h4fQ"> <img alt="Screenshot 2024-06-21 at 10 09 59 PM" width="469" src="https://private-user-images.githubusercontent.com/28274230/341937412-bfbba68e-d32e-4016-ad21-80c3c9697482.png?jwt=eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJnaXRodWIuY29tIiwiYXVkIjoicmF3LmdpdGh1YnVzZXJjb250ZW50LmNvbSIsImtleSI6ImtleTUiLCJleHAiOjE3MTk0MTE3MTksIm5iZiI6MTcxOTQxMTQxOSwicGF0aCI6Ii8yODI3NDIzMC8zNDE5Mzc0MTItYmZiYmE2OGUtZDMyZS00MDE2LWFkMjEtODBjM2M5Njk3NDgyLnBuZz9YLUFtei1BbGdvcml0aG09QVdTNC1ITUFDLVNIQTI1NiZYLUFtei1DcmVkZW50aWFsPUFLSUFWQ09EWUxTQTUzUFFLNFpBJTJGMjAyNDA2MjYlMkZ1cy1lYXN0LTElMkZzMyUyRmF3czRfcmVxdWVzdCZYLUFtei1EYXRlPTIwMjQwNjI2VDE0MTY1OVomWC1BbXotRXhwaXJlcz0zMDAmWC1BbXotU2lnbmF0dXJlPWQxMmZiMWVhNmU1ZWNiMjllZWM4NjdkZTllZjIwMjhjZGUyODQ3MGIyZTNkZTBmN2RmNDFlNGU5NDYzZjJhM2QmWC1BbXotU2lnbmVkSGVhZGVycz1ob3N0JmFjdG9yX2lkPTAma2V5X2lkPTAmcmVwb19pZD0wIn0.Wg5P3LChl7goqPBXjPRkPPhl8E2XsDa7mfL-fHFYuAo">

may be better to change AudioSchedler naming.

**Comment by SamKhoze** [comment]
@Maelstrom2014 @leiweiqiang @dancemanUK The code is updated, now you can load your audio with VHS Load Audio Node and you will not get this error.
