### ISSUE TITLE
Hi, after updating the comphui, the new load audio node does not connect to the audio in the  lipsync node.

### ISSUE THREAD

**Issue by gilushon** [SamKhoze/ComfyUI-DeepFuze#25]
Hi, after updating the comphui, the new load audio node does not connect to the audio in the  lipsync node.

**Comment by robbieprevost** [comment]
Same here.

**Comment by manniee07** [comment]
Same here

**Comment by SamKhoze** [comment]
@robbieprevost @manniee07 @gilushon the VHS node updated their load audio file also they created a new converter node to convert the legacy, I am fixing it so it works with the new VHS load audio
