### ISSUE TITLE
Installation via ComfyUI git UNINSTALLED everything!

### ISSUE THREAD

**Issue by piovis2023** [SamKhoze/ComfyUI-DeepFuze#27]
Hi

I followed your installation instructions: 
Comfyui manager -> Installed via git -> Repo URL

My terminal then gave me a choice (See screenshot). I selected 'default', and it uninstalled all of my comfyui drivers!

What went wrong?
<img width="395" alt="image" src="https://github.com/SamKhoze/ComfyUI-DeepFuze/assets/130514657/451132e4-6f57-4cd9-9164-307e17574793">

FYI my setup:
Windows 11 OS
Cuda env
Python 3.10
Cuda 1.2.1

**Comment by SamKhoze** [comment]
@piovis2023 please read the CUDA installation, you have to install Cuda 11.8
