### ISSUE TITLE
DeepFuze TTS Error - [WinError 267] The directory name is invalid

### ISSUE THREAD

**Issue by mmcc1** [SamKhoze/ComfyUI-DeepFuze#34]
DeepFuze generates the below error.  

Setup:
1. A clean install of Comfy-UI
2. Updated VHS
3. Latest Deepfuze (tried both through Manager and Git)
4. Dropped all Nodes and recreated workflow (based on DeepFuze_VoiceClonning_Lipsync.json).
5. Properly install CUDA support (both CUDA and CPU give the same error)

Error:
> !!! Exception during processing!!! [WinError 267] The directory name is invalid
> Traceback (most recent call last):
>   File "C:\ComfyUI-master\execution.py", line 151, in recursive_execute
>     output_data, output_ui = get_output_data(obj, input_data_all)
>                              ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
>   File "C:\ComfyUI-master\execution.py", line 81, in get_output_data
>     return_values = map_node_over_list(obj, input_data_all, obj.FUNCTION, allow_interrupt=True)
>                     ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
>   File "C:\ComfyUI-master\execution.py", line 74, in map_node_over_list
>     results.append(getattr(obj, func)(**slice_dict(input_data_all, i)))
>                    ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
>   File "C:\ComfyUI-master\custom_nodes\ComfyUI-DeepFuze\nodes.py", line 1431, in generate_audio
>     result = subprocess.run(command,cwd="ComfyUI/custom_nodes/ComfyUI-DeepFuze",stdout=subprocess.PIPE)
>              ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
>   File "C:\Python\Python312\Lib\subprocess.py", line 548, in run
>     with Popen(*popenargs, **kwargs) as process:
>          ^^^^^^^^^^^^^^^^^^^^^^^^^^^
>   File "C:\Python\Python312\Lib\subprocess.py", line 1026, in __init__
>     self._execute_child(args, executable, preexec_fn, close_fds,
>   File "C:\Python\Python312\Lib\subprocess.py", line 1538, in _execute_child
>     hp, ht, pid, tid = _winapi.CreateProcess(executable, args,
>                        ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
> NotADirectoryError: [WinError 267] The directory name is invalid

**Comment by mmcc1** [comment]
Noticed that a requirement, trainer>=0.0.36, is missing.  Install generates the following error in Python 3.12.3.

> ERROR: Ignored the following versions that require a different python version: 0.0.10 Requires-Python >=3.6.0, <3.10; 0.0.11 Requires-Python >=3.6.0, <3.11; 0.0.12 Requires-Python >=3.6.0, <3.11; 0.0.13 Requires-Python >=3.6.0, <3.11; 0.0.14 Requires-Python >=3.6.0, <3.11; 0.0.15 Requires-Python >=3.6.0, <3.11; 0.0.16 Requires-Python >=3.6.0, <3.11; 0.0.17 Requires-Python >=3.6.0, <3.11; 0.0.18 Requires-Python >=3.6.0, <3.11; 0.0.19 Requires-Python >=3.6.0, <3.11; 0.0.20 Requires-Python >=3.6.0, <3.11; 0.0.21 Requires-Python >=3.6.0, <3.11; 0.0.22 Requires-Python >=3.6.0, <3.11; 0.0.23 Requires-Python >=3.6.0, <3.11; 0.0.24 Requires-Python >=3.6.0, <3.11; 0.0.25 Requires-Python >=3.6.0, <3.11; 0.0.26 Requires-Python >=3.6.0, <3.11; 0.0.27 Requires-Python >=3.6.0, <3.12; 0.0.28 Requires-Python >=3.6.0, <3.12; 0.0.29 Requires-Python >=3.6.0, <3.12; 0.0.30 Requires-Python >=3.6.0, <3.12; 0.0.31 Requires-Python >=3.6.0, <3.12; 0.0.32 Requires-Python >=3.6.0, <3.12; 0.0.33 Requires-Python >=3.6.0, <3.12; 0.0.34 Requires-Python >=3.6.0, <3.12; 0.0.35 Requires-Python >=3.6.0, <3.12; 0.0.36 Requires-Python >=3.6.0, <3.12; 0.0.5 Requires-Python >=3.6.0, <3.10; 0.0.6 Requires-Python >=3.6.0, <3.10; 0.0.7 Requires-Python >=3.6.0, <3.10; 0.0.8 Requires-Python >=3.6.0, <3.10; 0.0.9 Requires-Python >=3.6.0, <3.10
> ERROR: Could not find a version that satisfies the requirement trainer (from versions: none)
> ERROR: No matching distribution found for trainer

**Comment by SamKhoze** [comment]
Hello @mmcc1,
Are you using conda or other env to run the comfy?

**Comment by mmcc1** [comment]
> Hello @mmcc1, Are you using conda or other env to run the comfy?

No, just Python on Win 11.

**Comment by SamKhoze** [comment]
I had update the code can you try again with updated code

**Comment by mmcc1** [comment]
> I had update the code can you try again with updated code

That fixed the TTS issue.  Thanks.
