### ISSUE TITLE
DeepFuze TTS Not Generating Audio

### ISSUE THREAD

**Issue by mmcc1** [SamKhoze/ComfyUI-DeepFuze#35]
DeepFuze TTS is not generating a cloned voice.  Instead, it is copying the input mp3.

The log window has the following error:

> Traceback (most recent call last):
>   File "C:\ComfyUI-master\custom_nodes\ComfyUI-DeepFuze\tts_generation.py", line 10, in <module>
>     from TTS.api import TTS
>   File "C:\ComfyUI-master\custom_nodes\ComfyUI-DeepFuze\TTS\api.py", line 10, in <module>
>     from TTS.utils.manage import ModelManager
>   File "C:\ComfyUI-master\custom_nodes\ComfyUI-DeepFuze\TTS\utils\manage.py", line 14, in <module>
>     from TTS.config import load_config, read_json_with_comments
>   File "C:\ComfyUI-master\custom_nodes\ComfyUI-DeepFuze\TTS\config\__init__.py", line 10, in <module>
>     from TTS.config.shared_configs import *
>   File "C:\ComfyUI-master\custom_nodes\ComfyUI-DeepFuze\TTS\config\shared_configs.py", line 5, in <module>
>     from trainer import TrainerConfig
> ModuleNotFoundError: No module named 'trainer'

trainer>=0.0.36, is missing.  Install generates the following error in Python 3.12.3.

> ERROR: Ignored the following versions that require a different python version: 0.0.10 Requires-Python >=3.6.0, <3.10; 0.0.11 Requires-Python >=3.6.0, <3.11; 0.0.12 Requires-Python >=3.6.0, <3.11; 0.0.13 Requires-Python >=3.6.0, <3.11; 0.0.14 Requires-Python >=3.6.0, <3.11; 0.0.15 Requires-Python >=3.6.0, <3.11; 0.0.16 Requires-Python >=3.6.0, <3.11; 0.0.17 Requires-Python >=3.6.0, <3.11; 0.0.18 Requires-Python >=3.6.0, <3.11; 0.0.19 Requires-Python >=3.6.0, <3.11; 0.0.20 Requires-Python >=3.6.0, <3.11; 0.0.21 Requires-Python >=3.6.0, <3.11; 0.0.22 Requires-Python >=3.6.0, <3.11; 0.0.23 Requires-Python >=3.6.0, <3.11; 0.0.24 Requires-Python >=3.6.0, <3.11; 0.0.25 Requires-Python >=3.6.0, <3.11; 0.0.26 Requires-Python >=3.6.0, <3.11; 0.0.27 Requires-Python >=3.6.0, <3.12; 0.0.28 Requires-Python >=3.6.0, <3.12; 0.0.29 Requires-Python >=3.6.0, <3.12; 0.0.30 Requires-Python >=3.6.0, <3.12; 0.0.31 Requires-Python >=3.6.0, <3.12; 0.0.32 Requires-Python >=3.6.0, <3.12; 0.0.33 Requires-Python >=3.6.0, <3.12; 0.0.34 Requires-Python >=3.6.0, <3.12; 0.0.35 Requires-Python >=3.6.0, <3.12; 0.0.36 Requires-Python >=3.6.0, <3.12; 0.0.5 Requires-Python >=3.6.0, <3.10; 0.0.6 Requires-Python >=3.6.0, <3.10; 0.0.7 Requires-Python >=3.6.0, <3.10; 0.0.8 Requires-Python >=3.6.0, <3.10; 0.0.9 Requires-Python >=3.6.0, <3.10
> ERROR: Could not find a version that satisfies the requirement trainer (from versions: none)
> ERROR: No matching distribution found for trainer

There is a suggestion here to use a replacement:
https://github.com/coqui-ai/Trainer/issues/146

Opened a bug report to request a new build of trainer
https://github.com/coqui-ai/Trainer/issues/147

**Comment by mmcc1** [comment]
I added the fork of trainer:

> pip install coqui-tts-trainer

This seems to have fixed the dependency error, but I'm now getting an error about a missing config.json file.

> Traceback (most recent call last):
>   File "C:\ComfyUI-master\custom_nodes\ComfyUI-DeepFuze\tts_generation.py", line 36, in <module>
>     main()
>   File "C:\ComfyUI-master\custom_nodes\ComfyUI-DeepFuze\tts_generation.py", line 30, in main
>     tts = TTS(model_path=args.model,config_path=os.path.join(args.model,"config.json")).to(device)
>           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
>   File "C:\ComfyUI-master\custom_nodes\ComfyUI-DeepFuze\TTS\api.py", line 65, in __init__
>     self.config = load_config(config_path) if config_path else None
>                   ^^^^^^^^^^^^^^^^^^^^^^^^
>   File "C:\ComfyUI-master\custom_nodes\ComfyUI-DeepFuze\TTS\config\__init__.py", line 88, in load_config
>     with fsspec.open(config_path, "r", encoding="utf-8") as f:
>   File "C:\Python\Python312\Lib\site-packages\fsspec\core.py", line 105, in __enter__
>     f = self.fs.open(self.path, mode=mode)
>         ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
>   File "C:\Python\Python312\Lib\site-packages\fsspec\spec.py", line 1303, in open
>     f = self._open(
>         ^^^^^^^^^^^
>   File "C:\Python\Python312\Lib\site-packages\fsspec\implementations\local.py", line 191, in _open
>     return LocalFileOpener(path, mode, fs=self, **kwargs)
>            ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
>   File "C:\Python\Python312\Lib\site-packages\fsspec\implementations\local.py", line 355, in __init__
>     self._open()
>   File "C:\Python\Python312\Lib\site-packages\fsspec\implementations\local.py", line 360, in _open
>     self.f = open(self.path, mode=self.mode)
>              ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
> FileNotFoundError: [Errno 2] No such file or directory: 'C:/ComfyUI-master/models/deepfuze/config.json'

**Comment by SamKhoze** [comment]
@mmcc1 Did you download models?

**Comment by mmcc1** [comment]
> @mmcc1 Did you download models?

That was it.  I thought that section of the ReadMe was for the Mac, so I skipped over it.  Seems to be working now.
