### ISSUE TITLE
What to fill in deepfuze.load_checkpoint?

### ISSUE THREAD

**Issue by andreclaudino** [SamKhoze/ComfyUI-DeepFuze#39]
When executing programmatically, there is a step when the function `deepfuze.load_checkpoint('path/to/checkpoint_path')` is called. Which is the argument? There is no instructions on how to download checkpoint and no documentation on what is the path. Can you help with that?

**Comment by SamKhoze** [comment]
Hello @andreclaudino,

here is the download link [Google Drive](https://drive.google.com/drive/folders/1CNdsf_M1cBLgFIS5HQIqm0lCoW4M4QkL?usp=sharing) it is also provided in the Readme.md file

Thank you
