### ISSUE TITLE
Your requirements.txt is too specific

### ISSUE THREAD

**Issue by ManOrMonster** [SamKhoze/ComfyUI-DeepFuze#7]
This node broke other nodes. I'm assuming it's because of the requirements.txt with very specific requirements.

**Comment by SamKhoze** [comment]
Hello @ManOrMonster,

can you let me know what are the dependencies or packages is conflicting?

**Comment by ManOrMonster** [comment]
Numpy was one. It broke [ComfyUI-Mana-Nodes](https://github.com/ForeignGods/ComfyUI-Mana-Nodes) and I think at least one other custom node, but I don't remember which, and my log for yesterday is gone now. I was getting Numpy errors for sure.

Long story short, I ended up uninstalling this node then using "try fixing" from Manager on Mana Nodes, and it miraculously solved the issue.

**Comment by kelvinyoung** [comment]
> Numpy was one. It broke [ComfyUI-Mana-Nodes](https://github.com/ForeignGods/ComfyUI-Mana-Nodes) and I think at least one other custom node, but I don't remember which, and my log for yesterday is gone now. I was getting Numpy errors for sure.
> 
> Long story short, I ended up uninstalling this node then using "try fixing" from Manager on Mana Nodes, and it miraculously solved the issue.

Ya, when TTS requires numpy==1.22.0, meanwhile scipy requires 1.24.6

**Comment by SamKhoze** [comment]
Now you don't need to install TTS externally and we integrated it in with our current repo

**Comment by ManOrMonster** [comment]
The current requirements.txt has librosa, scipy, and tqdm listed twice.

**Comment by SamKhoze** [comment]
Thanks for letting me know It is updated.
